In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


data = {
    'Disease': [
        'diseased','not diseased','diseased','diseased','not diseased',
        'not diseased','diseased','diseased','not diseased','not diseased',
        'diseased','diseased','diseased','diseased','not diseased',
        'diseased','not diseased','not diseased','diseased','diseased',
        'diseased','diseased','not diseased','not diseased','not diseased',
        'not diseased','diseased','not diseased','diseased','not diseased',
        'diseased','diseased','diseased','diseased','not diseased','not diseased'
    ],

    'Age': [
        43,18,22,25,45,12,23,33,27,27,
        48,34,32,66,24,34,27,34,55,65,
        44,88,33,43,32,66,24,34,27,34,
        55,65,44,88,33,43
    ],

    'Gender': [
        'Male','Male','Female','Male','Female','Male','Male','Male',
        'Male','Female','Female','Female','Female','Male','Male',
        'Male','Male','Female','Male','Male','Male','Male','Male',
        'Male','Female','Female','Male','Male','Male','Female',
        'Female','Female','Male','Male','Male','Female'
    ],

    'Smoker_status': [
        'Smoker','Smoker','Non-smoker','Non-smoker','Smoker',
        'Non-smoker','Smoker','Smoker','Non-smoker','Non-smoker',
        'Smoker','Smoker','Smoker','Smoker','Smoker','Non-smoker',
        'Non-smoker','Smoker','Smoker','Smoker','Smoker','Non-smoker',
        'Non-smoker','Non-smoker','Non-smoker','Smoker','Smoker',
        'Non-smoker','Non-smoker','Non-smoker','Smoker','Smoker',
        'Smoker','Non-smoker','Non-smoker','Non-smoker'
    ]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

         Disease  Age  Gender Smoker_status
0       diseased   43    Male        Smoker
1   not diseased   18    Male        Smoker
2       diseased   22  Female    Non-smoker
3       diseased   25    Male    Non-smoker
4   not diseased   45  Female        Smoker
5   not diseased   12    Male    Non-smoker
6       diseased   23    Male        Smoker
7       diseased   33    Male        Smoker
8   not diseased   27    Male    Non-smoker
9   not diseased   27  Female    Non-smoker
10      diseased   48  Female        Smoker
11      diseased   34  Female        Smoker
12      diseased   32  Female        Smoker
13      diseased   66    Male        Smoker
14  not diseased   24    Male        Smoker
15      diseased   34    Male    Non-smoker
16  not diseased   27    Male    Non-smoker
17  not diseased   34  Female        Smoker
18      diseased   55    Male        Smoker
19      diseased   65    Male        Smoker
20      diseased   44    Male        Smoker
21      diseased   88    Male    Non-smoker
22  not diseased   33    Male    Non-smoker
23  not diseased   43    Male    Non-smoker
24  not diseased   32  Female    Non-smoker
25  not diseased   66  Female        Smoker
26      diseased   24    Male        Smoker
27  not diseased   34    Male    Non-smoker
28      diseased   27    Male    Non-smoker
29  not diseased   34  Female    Non-smoker
30      diseased   55  Female        Smoker
31      diseased   65  Female        Smoker
32      diseased   44    Male        Smoker
33      diseased   88    Male    Non-smoker
34  not diseased   33    Male    Non-smoker
35  not diseased   43  Female    Non-smoker

In [2]:
# Disease: Not Diseased = 0, Diseased = 1
df['Disease'] = df['Disease'].map({
    'not diseased': 0,
    'diseased': 1
})

# Gender: Female = 0, Male = 1
df['Gender'] = df['Gender'].map({
    'Female': 0,
    'Male': 1
})

# Smoker status: Non-smoker = 0, Smoker = 1
df['Smoker_status'] = df['Smoker_status'].map({
    'Non-smoker': 0,
    'Smoker': 1
})

print("Encoded Dataset:")
display(df)

Encoded Dataset:

    Disease  Age  Gender  Smoker_status
0         1   43       1              1
1         0   18       1              1
2         1   22       0              0
3         1   25       1              0
4         0   45       0              1
5         0   12       1              0
6         1   23       1              1
7         1   33       1              1
8         0   27       1              0
9         0   27       0              0
10        1   48       0              1
11        1   34       0              1
12        1   32       0              1
13        1   66       1              1
14        0   24       1              1
15        1   34       1              0
16        0   27       1              0
17        0   34       0              1
18        1   55       1              1
19        1   65       1              1
20        1   44       1              1
21        1   88       1              0
22        0   33       1              0
23        0   43       1              0
24        0   32       0              0
25        0   66       0              1
26        1   24       1              1
27        0   34       1              0
28        1   27       1              0
29        0   34       0              0
30        1   55       0              1
31        1   65       0              1
32        1   44       1              1
33        1   88       1              0
34        0   33       1              0
35        0   43       0              0

In [3]:
# Independent variables
X = df[['Age', 'Gender', 'Smoker_status']]

# Dependent variable
y = df['Disease']

print("Independent Variables (X):")
display(X)

print("Dependent Variable (y):")
display(y)

Independent Variables (X):

    Age  Gender  Smoker_status
0    43       1              1
1    18       1              1
2    22       0              0
3    25       1              0
4    45       0              1
5    12       1              0
6    23       1              1
7    33       1              1
8    27       1              0
9    27       0              0
10   48       0              1
11   34       0              1
12   32       0              1
13   66       1              1
14   24       1              1
15   34       1              0
16   27       1              0
17   34       0              1
18   55       1              1
19   65       1              1
20   44       1              1
21   88       1              0
22   33       1              0
23   43       1              0
24   32       0              0
25   66       0              1
26   24       1              1
27   34       1              0
28   27       1              0
29   34       0              0
30   55       0              1
31   65       0              1
32   44       1              1
33   88       1              0
34   33       1              0
35   43       0              0

Dependent Variable (y):

0     1
1     0
2     1
3     1
4     0
5     0
6     1
7     1
8     0
9     0
10    1
11    1
12    1
13    1
14    0
15    1
16    0
17    0
18    1
19    1
20    1
21    1
22    0
23    0
24    0
25    0
26    1
27    0
28    1
29    0
30    1
31    1
32    1
33    1
34    0
35    0
Name: Disease, dtype: int64

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:")
display(X_train)

print("Testing data:")
display(X_test)

Training data:

    Age  Gender  Smoker_status
9    27       0              0
23   43       1              0
1    18       1              1
0    43       1              1
25   66       0              1
11   34       0              1
30   55       0              1
12   32       0              1
31   65       0              1
28   27       1              0
6    23       1              1
35   43       0              0
4    45       0              1
21   88       1              0
7    33       1              1
13   66       1              1
34   33       1              0
26   24       1              1
5    12       1              0
22   33       1              0
32   44       1              1
29   34       0              0
14   24       1              1
20   44       1              1
15   34       1              0
17   34       0              1
3    25       1              0
18   55       1              1

Testing data:

    Age  Gender  Smoker_status
33   88       1              0
2    22       0              0
27   34       1              0
16   27       1              0
24   32       0              0
10   48       0              1
8    27       1              0
19   65       1              1

In [5]:
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.

In [6]:
y_pred = model.predict(X_test)

print("Actual values:")
print(y_test.values)

print("\nPredicted values:")
print(y_pred)

Actual values:
[1 1 0 0 0 1 0 1]

Predicted values:
[1 0 0 0 0 1 0 1]

In [7]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

Accuracy: 0.875
Accuracy Percentage: 87.5 %

In [8]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[4 0]
 [1 3]]

In [9]:
print("Classification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=['Not Diseased', 'Diseased']
))

Classification Report:
              precision    recall  f1-score   support

Not Diseased       0.80      1.00      0.89         4
    Diseased       1.00      0.75      0.86         4

    accuracy                           0.88         8
   macro avg       0.90      0.88      0.87         8
weighted avg       0.90      0.88      0.87         8

In [10]:
new_person = pd.DataFrame({
    'Age': [35],
    'Gender': [1],          # Male
    'Smoker_status': [1]    # Smoker
})

prediction = model.predict(new_person)
probability = model.predict_proba(new_person)

if prediction[0] == 1:
    print("Prediction: DISEASED")
else:
    print("Prediction: NOT DISEASED")

print("Probability of Not Diseased:", probability[0][0])
print("Probability of Diseased:", probability[0][1])

Prediction: DISEASED
Probability of Not Diseased: 0.3010628567247505
Probability of Diseased: 0.6989371432752495

In [11]:
df.to_csv('final_logistic_regression_dataset.csv', index=False)

print("Final CSV created successfully!")

Final CSV created successfully!

In [12]:
from google.colab import files

files.download('final_logistic_regression_dataset.csv')