In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Create the dataset
data = {
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age': [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male',
               'Female', 'Female', 'Female', 'Female', 'Female']
}

df = pd.DataFrame(data)

# Display the dataset
print("Dataset:")
display(df)

Dataset:

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [2]:
# Encode Gender
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

print("Dataset after encoding Gender:")
display(df)

Dataset after encoding Gender:

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1
5      55    1.55   18       0
6      69    1.50   89       0
7      71    1.78   42       0
8      64    1.67   16       0
9      69    1.64   52       0

In [3]:
# Independent variables
X = df[['Height', 'Age', 'Gender']]

# Dependent variable
y = df['Weight']

print("Independent variables:")
display(X)

print("Dependent variable:")
display(y)

Independent variables:

   Height  Age  Gender
0    1.80   35       1
1    1.68   39       1
2    1.82   25       1
3    1.70   60       1
4    1.87   27       1
5    1.55   18       0
6    1.50   89       0
7    1.78   42       0
8    1.67   16       0
9    1.64   52       0

Dependent variable:

0    79
1    69
2    73
3    95
4    82
5    55
6    69
7    71
8    64
9    69
Name: Weight, dtype: int64

In [4]:
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:")
print(X_train)

print("\nTesting data:")
print(X_test)

Training data:
   Height  Age  Gender
5    1.55   18       0
0    1.80   35       1
7    1.78   42       0
2    1.82   25       1
9    1.64   52       0
4    1.87   27       1
3    1.70   60       1
6    1.50   89       0

Testing data:
   Height  Age  Gender
8    1.67   16       0
1    1.68   39       1

In [5]:
# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

print("Model trained successfully.")

Model trained successfully.

In [6]:
# Model coefficients
print("Intercept:", model.intercept_)

print("Coefficients:")
print("Height:", model.coef_[0])
print("Age:", model.coef_[1])
print("Gender:", model.coef_[2])

Intercept: -3.0552172392595196
Coefficients:
Height: 32.83533630032696
Age: 0.3172947417608091
Gender: 14.623118479712073

In [7]:
# Predict weight for test data
y_pred = model.predict(X_test)

print("Actual vs Predicted Weight:")

result = pd.DataFrame({
    'Actual Weight': y_test.values,
    'Predicted Weight': y_pred
})

display(result)

Actual vs Predicted Weight:

   Actual Weight  Predicted Weight
0             64         56.856510
1             69         79.105761

In [8]:
# Calculate Mean Squared Error
mse = mean_squared_error(y_test, y_pred)

# Calculate R-squared
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("R-squared (R²):", r2)

Mean Squared Error (MSE): 76.57792714844265
R-squared (R²): -11.252468343750825

In [9]:
# New person's data
new_person = pd.DataFrame({
    'Height': [1.75],
    'Age': [30],
    'Gender': [1]
})

# Predict weight
predicted_weight = model.predict(new_person)

print("Predicted weight:", predicted_weight[0], "kg")

Predicted weight: 78.548582018849 kg

In [10]:
# Save dataset as CSV
df.to_csv('body_weight_dataset.csv', index=False)

print("Dataset saved as body_weight_dataset.csv")

Dataset saved as body_weight_dataset.csv

In [11]:
from google.colab import files

files.download('body_weight_dataset.csv')